import os

import boto3

dynamoDB = boto3.resource("dynamodb")


def handler(event, context):
    try:
        ERROR_CODE_TABLE_NAME = os.environ["ERROR_CODE_TABLE_NAME"]

        insert_error_info(
            ERROR_CODE_TABLE_NAME,
        )

    except Exception as e:
        print(e)


def insert_error_info(
    error_code_table_name: str,
):
    initial_data = set_initial_data()
    table = dynamoDB.Table(error_code_table_name)
    for item in initial_data:
        table.put_item(Item=item)


def set_initial_data():
    initial_data = [
        {
            "address": "F",
            "error_code": "1",
            "category": "F0001",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "全体",
            "alert_detail": "0001 : PLCシステム異常",
            "how_to_recover": "",
            "invoke_condition": "SM1 : 自己診断エラー ON",
            "object_of_stop": "全て",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "2",
            "category": "F0002",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "3",
            "category": "F0003",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "4",
            "category": "F0004",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "5",
            "category": "F0005",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "6",
            "category": "F0006",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "7",
            "category": "F0007",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "8",
            "category": "F0008",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "9",
            "category": "F0009",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "10",
            "category": "F0010",
            "severity": "HIGH",
            "tag_name": "water_poweroff_pv",
            "tag_description": "給水ポンプ電源OFF（現在値）",
            "device_type": "給水ポンプ",
            "alert_detail": "0010 : 給水ポンプ 断線",
            "how_to_recover": "",
            "invoke_condition": "起動後10秒経過しても流量センサーで値が検出されない",
            "object_of_stop": "給水ポンプ",
            "how_to_invoke": "ポンプ用電源OFF",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "11",
            "category": "F0011",
            "severity": "HIGH",
            "tag_name": "water_pressure_pv",
            "tag_description": "給水ポンプ圧力（現在値）",
            "device_type": "電磁バルブ",
            "alert_detail": "0011 : 給水側電磁バルブ異常",
            "how_to_recover": "",
            "invoke_condition": "給水側圧力センサーで0.8MPa以上を示す",
            "object_of_stop": "給水ポンプ",
            "how_to_invoke": "電磁バルブ用電源OFF",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "12",
            "category": "F0012",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "13",
            "category": "F0013",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "14",
            "category": "F0014",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "15",
            "category": "F0015",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "16",
            "category": "F0016",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "17",
            "category": "F0017",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "18",
            "category": "F0018",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "19",
            "category": "F0019",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "20",
            "category": "F0020",
            "severity": "HIGH",
            "tag_name": "drain_poweroff_pv",
            "tag_description": "排水ポンプ電源OFF（現在値）",
            "device_type": "排水ポンプ",
            "alert_detail": "0020 : 排水ポンプ 断線",
            "how_to_recover": "ポンプ用電源ON",
            "invoke_condition": "起動後10秒経過しても流量センサーで値が検出されない",
            "object_of_stop": "排水ポンプ",
            "how_to_invoke": "ポンプ用電源OFF",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "21",
            "category": "F0021",
            "severity": "HIGH",
            "tag_name": "drain_pressure_pv",
            "tag_description": "排水ポンプ圧力（現在値）",
            "device_type": "電磁バルブ",
            "alert_detail": "0021 : 排水側電磁バルブ異常",
            "how_to_recover": "",
            "invoke_condition": "排水側圧力センサーで0.8MPa以上を示す",
            "object_of_stop": "排水ポンプ",
            "how_to_invoke": "電磁バルブ用電源OFF",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "22",
            "category": "F0022",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "23",
            "category": "F0023",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "24",
            "category": "F0024",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "25",
            "category": "F0025",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "26",
            "category": "F0026",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "27",
            "category": "F0027",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "28",
            "category": "F0028",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "29",
            "category": "F0029",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "30",
            "category": "F0030",
            "severity": "HIGH",
            "tag_name": "tank_poweroff_pv",
            "tag_description": "撹拌機電源OFF（現在値）",
            "device_type": "モーター",
            "alert_detail": "0030 : モーター断線",
            "how_to_recover": "",
            "invoke_condition": "モーターの負荷電圧が0V",
            "object_of_stop": "モーター",
            "how_to_invoke": "モーター用電源OFF",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "31",
            "category": "F0031",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "32",
            "category": "F0032",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "33",
            "category": "F0033",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "34",
            "category": "F0034",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "35",
            "category": "F0035",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "36",
            "category": "F0036",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "37",
            "category": "F0037",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "38",
            "category": "F0038",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "39",
            "category": "F0039",
            "severity": "HIGH",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "how_to_recover": "",
            "invoke_condition": "",
            "object_of_stop": "",
            "how_to_invoke": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "50",
            "category": "F050",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "51",
            "category": "F051",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "52",
            "category": "F052",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "53",
            "category": "F053",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "54",
            "category": "F054",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "55",
            "category": "F055",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "56",
            "category": "F056",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "57",
            "category": "F057",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "58",
            "category": "F058",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "59",
            "category": "F059",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "60",
            "category": "F060",
            "severity": "LOW",
            "tag_name": "water_voltage_pv",
            "tag_description": "給水ポンプ電圧（現在値）",
            "device_type": "給水ポンプ",
            "alert_detail": "給水ポンプ 異常",
            "invoke_condition": "給水ポンプの電圧が6vを下回る",
            "how_to_invoke": "変圧器で6v以下に設定",
            "stop_condition": "給水ポンプの電圧が6v以上になる",
            "how_to_recover": "変圧器の電圧をもとに戻す（手動）",
            "object_of_stop": "給水ポンプ",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "61",
            "category": "F061",
            "severity": "LOW",
            "tag_name": "water_flow_pv",
            "tag_description": "給水ポンプ流量（現在値）",
            "device_type": "給水ポンプ",
            "alert_detail": "給水ポンプ異常",
            "invoke_condition": "ポンプ電圧正常。流量センサーの計測値が、2L/minを下回る",
            "how_to_invoke": "手動バルブで配管の流量を下げる",
            "stop_condition": "",
            "how_to_recover": "手動弁で元の側に切り替え実施",
            "object_of_stop": "給水ポンプ",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "62",
            "category": "F062",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "63",
            "category": "F063",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "64",
            "category": "F064",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "65",
            "category": "F065",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "66",
            "category": "F066",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "67",
            "category": "F067",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "68",
            "category": "F068",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "69",
            "category": "F069",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "70",
            "category": "F070",
            "severity": "LOW",
            "tag_name": "drain_voltage_pv",
            "tag_description": "排水ポンプ電圧（現在値）",
            "device_type": "排水ポンプ",
            "alert_detail": "排水ポンプ 異常",
            "invoke_condition": "排水ポンプの電圧が6vを下回る\n\n上限幅：9 - 10.5v\n下限幅：6-7v",
            "how_to_invoke": "変圧器で6v以下に設定",
            "stop_condition": "",
            "how_to_recover": "変圧器の電圧をもとに戻す（手動）",
            "object_of_stop": "排水ポンプ",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "71",
            "category": "F071",
            "severity": "LOW",
            "tag_name": "drain_flow_pv",
            "tag_description": "排水ポンプ流量（現在値）",
            "device_type": "排水ポンプ",
            "alert_detail": "排水ポンプ異常",
            "invoke_condition": "ポンプ電圧正常。流量センサーの計測値が、2L/minを下回る",
            "how_to_invoke": "手動弁の開き具合を小さくする",
            "stop_condition": "",
            "how_to_recover": "手動弁で元の側に切り替え実施",
            "object_of_stop": "給水ポンプ",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "72",
            "category": "F072",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "73",
            "category": "F073",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "74",
            "category": "F074",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "75",
            "category": "F075",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "76",
            "category": "F076",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "77",
            "category": "F077",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "78",
            "category": "F078",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "79",
            "category": "F079",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "80",
            "category": "F080",
            "severity": "LOW",
            "tag_name": "tank_voltage_pv",
            "tag_description": "撹拌機電圧（現在値）",
            "device_type": "撹拌機",
            "alert_detail": "モーター異常",
            "invoke_condition": "モーターの電圧が6Vを下回る",
            "how_to_invoke": "変圧器で6v以下に設定",
            "stop_condition": "",
            "how_to_recover": "変圧器の電圧をもとに戻す（手動）",
            "object_of_stop": "モーター",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "81",
            "category": "F081",
            "severity": "LOW",
            "tag_name": "tank_rotation_pv",
            "tag_description": "撹拌機回転数（現在値）",
            "device_type": "撹拌機",
            "alert_detail": "モーター異常",
            "invoke_condition": "モーターと連動した回転計がxx RPMを下回る",
            "how_to_invoke": "手で撹拌機の回転を邪魔させる",
            "stop_condition": "",
            "how_to_recover": "手を放す",
            "object_of_stop": "モーター",
            "others": "今回の実装からは外す",
        },
        {
            "address": "F",
            "error_code": "82",
            "category": "F082",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "83",
            "category": "F083",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "84",
            "category": "F084",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "85",
            "category": "F085",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "86",
            "category": "F086",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "87",
            "category": "F087",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "88",
            "category": "F088",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
        {
            "address": "F",
            "error_code": "89",
            "category": "F089",
            "severity": "LOW",
            "tag_name": "",
            "tag_description": "",
            "device_type": "",
            "alert_detail": "",
            "invoke_condition": "",
            "how_to_invoke": "",
            "stop_condition": "",
            "how_to_recover": "",
            "object_of_stop": "",
            "others": "",
        },
    ]

    return initial_data
